import type { PosStateV1 } from './types';

export const POS_SEED_V1: PosStateV1 = {
  version: 1,
  inventory: [
    { id: 'INV-CHICKEN', name: 'Chicken (boneless)', category: 'Proteins', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 8000, unit: 'g', costPerUnit: 0.0065, minLevel: 1500 },
    { id: 'INV-BUN', name: 'Burger Bun', category: 'Dry Goods', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 200, unit: 'pcs', costPerUnit: 0.25, minLevel: 12 },
    { id: 'INV-LETTUCE', name: 'Lettuce', category: 'Produce', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 2000, unit: 'g', costPerUnit: 0.0018, minLevel: 400 },
    { id: 'INV-TOMATO', name: 'Tomato', category: 'Produce', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 2500, unit: 'g', costPerUnit: 0.0022, minLevel: 500 },
    { id: 'INV-MAYO', name: 'Mayonnaise', category: 'Dry Goods', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 1200, unit: 'g', costPerUnit: 0.0035, minLevel: 250 },
    { id: 'INV-KETCHUP', name: 'Ketchup', category: 'Dry Goods', dishCategory: 'Burger', dishName: 'Chicken Burger', quantity: 900, unit: 'g', costPerUnit: 0.003, minLevel: 200 },
    { id: 'INV-OIL', name: 'Oil', category: 'Dry Goods', dishCategory: 'General', dishName: '', quantity: 1500, unit: 'ml', costPerUnit: 0.0012, minLevel: 300 },
    { id: 'INV-POTATO', name: 'Potato', category: 'Produce', dishCategory: 'General', dishName: 'Fries', quantity: 6000, unit: 'g', costPerUnit: 0.0011, minLevel: 1200 },
    { id: 'INV-SALT', name: 'Salt', category: 'Dry Goods', dishCategory: 'General', dishName: '', quantity: 1000, unit: 'g', costPerUnit: 0.0002, minLevel: 200 },
    { id: 'INV-COLA', name: 'Cola (bottles)', category: 'Beverages', dishCategory: 'Drinks', dishName: 'Cola', quantity: 24, unit: 'pcs', costPerUnit: 0.65, minLevel: 6 },
  ],
  recipes: [
    {
      id: 'REC-CHICKEN-BURGER',
      name: 'Chicken Burger',
      category: 'Burger',
      prepTime: 10,
      cookTime: 8,
      ingredients: [
        { inventoryId: 'INV-CHICKEN', qty: 150, unit: 'g' },
        { inventoryId: 'INV-BUN', qty: 1, unit: 'pcs' },
        { inventoryId: 'INV-LETTUCE', qty: 20, unit: 'g' },
        { inventoryId: 'INV-TOMATO', qty: 30, unit: 'g' },
        { inventoryId: 'INV-MAYO', qty: 15, unit: 'g' },
        { inventoryId: 'INV-KETCHUP', qty: 15, unit: 'g' },
        { inventoryId: 'INV-OIL', qty: 10, unit: 'ml' },
      ],
      instructions: 'Grill chicken. Toast bun. Assemble with sauces and veggies.',
    },
    {
      id: 'REC-FRIES',
      name: 'Fries',
      category: 'General',
      prepTime: 5,
      cookTime: 6,
      ingredients: [
        { inventoryId: 'INV-POTATO', qty: 250, unit: 'g' },
        { inventoryId: 'INV-OIL', qty: 25, unit: 'ml' },
        { inventoryId: 'INV-SALT', qty: 2, unit: 'g' },
      ],
      instructions: 'Cut potatoes, fry in oil, season with salt.',
    },
    {
      id: 'REC-COLA',
      name: 'Cola',
      category: 'Beverages',
      prepTime: 1,
      cookTime: 0,
      ingredients: [{ inventoryId: 'INV-COLA', qty: 1, unit: 'pcs' }],
      instructions: 'Serve chilled bottle or pour over ice.',
    },
  ],
  menu: [
    { id: 'MENU-CHICKEN-BURGER', name: 'Chicken Burger', category: 'Burger', price: 9.99, recipeId: 'REC-CHICKEN-BURGER', posIcon: 'Sandwich' },
    { id: 'MENU-FRIES', name: 'Fries', category: 'General', price: 2.99, recipeId: 'REC-FRIES', posIcon: 'Pizza' },
    { id: 'MENU-COLA', name: 'Cola', category: 'Beverages', price: 1.99, recipeId: 'REC-COLA', posIcon: 'CupSoda' },
  ],
  orders: [],
  usage: [],
  vendors: [
    {
      id: 'VEN-METRO-PRODUCE',
      name: 'Metro Produce Co.',
      contactName: 'Alex Rivera',
      email: 'orders@metroproduce.example',
      phone: '+1 555-0101',
      address: '1200 Wholesale Row, District 4',
      accountNumber: 'ACC-77821',
      paymentTerms: 'Net 15',
      notes: 'Primary produce deliveries Tue/Fri.',
      active: true,
    },
    {
      id: 'VEN-ATLANTIC-PROTEINS',
      name: 'Atlantic Proteins',
      contactName: 'Jamie Chen',
      email: 'sales@atlanticproteins.example',
      phone: '+1 555-0102',
      address: '88 Dockside Way',
      accountNumber: 'ACC-99204',
      paymentTerms: 'Net 30',
      notes: 'Chicken and beef; min order 40 lb.',
      active: true,
    },
    {
      id: 'VEN-DRY-GOODS-DIRECT',
      name: 'Dry Goods Direct',
      contactName: 'Sam Brooks',
      email: 's.brooks@drygoods.example',
      phone: '+1 555-0199',
      address: 'PO Box 400',
      accountNumber: '',
      paymentTerms: 'COD',
      notes: 'Seasonal specials; call before pickup.',
      active: false,
    },
  ],
  promotions: [
    {
      id: 'PROMO-HAPPY-HOUR-10',
      name: 'Happy hour — 10% off',
      description: 'Ten percent off the entire check. Stack with staff discretion.',
      active: true,
      kind: 'percent_off' as const,
      percent: 10,
    },
    {
      id: 'PROMO-LUNCH-5-OFF',
      name: 'Lunch rush — flat amount off',
      description: 'Flat 5.00 off the list subtotal before tax (e.g. lunch window — set in house rules).',
      active: true,
      kind: 'fixed_off_order' as const,
      fixedAmount: 5,
    },
    {
      id: 'PROMO-BOGO-CHICKEN-BURGER',
      name: 'BOGO Chicken Burger',
      description: 'Buy one chicken burger, get another free (same item; charged qty = ceil(qty/2)).',
      active: true,
      kind: 'bogo_menu_item' as const,
      bogoMenuItemId: 'MENU-CHICKEN-BURGER',
    },
    {
      id: 'PROMO-COMBO-CLASSIC-3',
      name: 'Classic combo (burger + fries + cola)',
      description: 'When the cart includes 1× burger, 1× fries, and 1× cola, those three charge as one bundle. Extra items stay at list price.',
      active: true,
      kind: 'package_deal' as const,
      lines: [
        { menuItemId: 'MENU-CHICKEN-BURGER', qty: 1 },
        { menuItemId: 'MENU-FRIES', qty: 1 },
        { menuItemId: 'MENU-COLA', qty: 1 },
      ],
      bundlePrice: 11.99,
    },
  ],
};

